env:
  es6: true
  node: true
  browser: true
parser: '@typescript-eslint/parser'
plugins:
  - 'react-hooks'
extends:
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:@typescript-eslint/recommended'
parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: 'detect'
rules:
  no-case-declarations: off
  linebreak-style: off
  indent:
    - error
    - 4
    - { "SwitchCase": 1 }
  quotes:
    - error
    - single
  semi:
    - error
    - always
  '@typescript-eslint/no-unused-vars':
    - warn
    - vars: all
      args: after-used
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
      ignoreRestSiblings: true
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-extra-semi': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/no-use-before-define': off
  'react/prop-types': off
  'react/display-name': off

